# Generated by Django 5.0.6 on 2024-06-04 00:24

import datetime
import django.db.models.deletion
import django.utils.timezone
import main_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
                ('cant_disponible', models.PositiveIntegerField()),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=10)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('cid', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=36, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('asistente', 'Asistente Medico'), ('doctor', 'Doctor')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', main_app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=10)),
                ('cid', models.CharField(blank=True, max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('especialidad', models.CharField(choices=[('odontologia', 'Odontologia'), ('nutricionista', 'Nutricionista'), ('general', 'Medicina General'), ('pediatria', 'Pediatria'), ('orientacion', 'Orientación Estudiantil y Familiar')], max_length=15)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=10)),
                ('cid', models.CharField(blank=True, max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('doctor_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('diagnostico', models.TextField(max_length=250)),
                ('tratamiento', models.TextField(blank=True, max_length=250)),
                ('fecha_propuesta', models.DateTimeField(default=datetime.datetime(2024, 6, 5, 0, 24, 10, 96626, tzinfo=datetime.timezone.utc))),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.asistente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id_recipe', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_deseada', models.PositiveIntegerField()),
                ('nota', models.TextField(blank=True, max_length=250, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cita')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='medicamentos',
            field=models.ManyToManyField(through='main_app.Recipe', to='main_app.medicamento'),
        ),
    ]
