# Generated by Django 5.0.6 on 2024-06-11 22:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_paciente_email_alter_cita_fecha_propuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='email',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_propuesta',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 22, 48, 24, 855153, tzinfo=datetime.timezone.utc)),
        ),
    ]
