# Generated by Django 5.0.6 on 2024-06-12 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_doctor_direccion_alter_cita_fecha_propuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_propuesta',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 1, 49, 24, 183516, tzinfo=datetime.timezone.utc)),
        ),
    ]
