# Generated by Django 5.0.6 on 2024-06-13 00:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_asistente_user_ref_alter_cita_fecha_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_propuesta',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 0, 12, 6, 85779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
