# Generated by Django 5.0.6 on 2024-06-13 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_medicamento_creado_en_alter_cita_fecha_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_propuesta',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 1, 39, 45, 285482, tzinfo=datetime.timezone.utc)),
        ),
    ]
